## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: admin
#    password: admin
#    url: jdbc:mysql://localhost:3306/shop?useSSL=false
 #   schema: classpath:db/schema.sql
    data: classpath:db/data.sql
#    platform: mysql
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
#      dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379
#  freemarker:
#      cache: false




  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
