## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: admin
    url: jdbc:mysql://localhost:3306/shop?useSSL=false
#    schema: classpath:db/schema.sql
#    data: classpath:db/data.sql
    platform: mysql
  jpa:
    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379
  queries:
    users-query: select user_name, encryted_password, active from accounts where user_name=?
    roles-query: select user_name, user_role from accounts where user_name=?
