## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: admin
#    password: admin
#    url: jdbc:mysql://localhost:3306/test?useSSL=false
#    platform: mysql
#    schema: classpath:mysql.sql
#    data: classpath:mysql.sql

    initialization-mode: always
    continue-on-error: true
  jpa:
#    show-sql: true
#    generate-ddl: false
    hibernate:
      ddl-auto: create
#      dialect: org.hibernate.dialect.MySQL5Dialect

#  jackson:
#    default-property-inclusion: non_null
#  redis:
#    host: localhost
#    port: 6379
#  freemarker:
#      cache: false




  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
